controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_confirm_registration:
    path: '/confirm-registration/{token}'
    controller: 'App\Controller\RegistrationController::confirmRegistration'
